export interface FruitData {
  id: string;
  nameId: string;
  nameEn: string;
  emoji: string;
  peakMonths: number[];
  offMonths: number[];
  seasonalityType: 'strong' | 'moderate' | 'mild';
  growingRegions: string[];
  priceRange: { low: number; high: number };
  ramadanImpact: 'high' | 'medium' | 'low' | 'none';
  description: string;
}

export const FRUITS: FruitData[] = [
  {
    id: 'durian',
    nameId: 'Durian',
    nameEn: 'Durian',
    emoji: '🍈',
    peakMonths: [12, 1, 2],
    offMonths: [5, 6, 7, 8, 9],
    seasonalityType: 'strong',
    growingRegions: ['Sumatera Utara', 'Kalimantan Barat', 'Jawa Barat', 'Sulawesi Selatan'],
    priceRange: { low: 50000, high: 150000 },
    ramadanImpact: 'high',
    description: 'Raja buah tropis yang terkenal dengan aroma kuat dan rasa manis legit.',
  },
  {
    id: 'manggis',
    nameId: 'Manggis',
    nameEn: 'Mangosteen',
    emoji: '🟣',
    peakMonths: [1, 2, 3],
    offMonths: [6, 7, 8, 9],
    seasonalityType: 'strong',
    growingRegions: ['Jawa Barat', 'Sumatera Barat', 'Kalimantan Timur'],
    priceRange: { low: 30000, high: 80000 },
    ramadanImpact: 'medium',
    description: 'Ratu buah dengan kulit ungu tebal dan daging putih manis menyegarkan.',
  },
  {
    id: 'mangga',
    nameId: 'Mangga',
    nameEn: 'Mango',
    emoji: '🥭',
    peakMonths: [9, 10, 11],
    offMonths: [2, 3, 4],
    seasonalityType: 'strong',
    growingRegions: ['Jawa Timur', 'Jawa Barat', 'NTB', 'Sulawesi Selatan'],
    priceRange: { low: 15000, high: 45000 },
    ramadanImpact: 'high',
    description: 'Buah tropis favorit dengan varietas unggulan Harum Manis dan Gedong Gincu.',
  },
  {
    id: 'rambutan',
    nameId: 'Rambutan',
    nameEn: 'Rambutan',
    emoji: '🔴',
    peakMonths: [12, 1, 2],
    offMonths: [5, 6, 7, 8],
    seasonalityType: 'strong',
    growingRegions: ['Jawa Barat', 'Sumatera Utara', 'Kalimantan Selatan'],
    priceRange: { low: 15000, high: 50000 },
    ramadanImpact: 'medium',
    description: 'Buah berambut merah dengan daging putih manis dan segar.',
  },
  {
    id: 'alpukat',
    nameId: 'Alpukat',
    nameEn: 'Avocado',
    emoji: '🥑',
    peakMonths: [2, 3, 4, 5],
    offMonths: [8, 9, 10],
    seasonalityType: 'moderate',
    growingRegions: ['Jawa Barat', 'Jawa Timur', 'Sumatera Barat', 'Lampung'],
    priceRange: { low: 20000, high: 50000 },
    ramadanImpact: 'high',
    description: 'Buah mentega yang populer untuk jus dan campuran es buah.',
  },
  {
    id: 'semangka',
    nameId: 'Semangka',
    nameEn: 'Watermelon',
    emoji: '🍉',
    peakMonths: [4, 5, 6, 7, 8, 9],
    offMonths: [12, 1],
    seasonalityType: 'moderate',
    growingRegions: ['Jawa Timur', 'Jawa Tengah', 'NTB', 'Sulawesi Selatan'],
    priceRange: { low: 5000, high: 15000 },
    ramadanImpact: 'high',
    description: 'Buah besar berair yang menjadi favorit untuk berbuka puasa.',
  },
  {
    id: 'pisang',
    nameId: 'Pisang',
    nameEn: 'Banana',
    emoji: '🍌',
    peakMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    offMonths: [],
    seasonalityType: 'mild',
    growingRegions: ['Jawa Timur', 'Jawa Barat', 'Lampung', 'Sumatera Utara'],
    priceRange: { low: 8000, high: 25000 },
    ramadanImpact: 'high',
    description: 'Buah sepanjang tahun yang menjadi bahan utama kolak dan takjil.',
  },
  {
    id: 'pepaya',
    nameId: 'Pepaya',
    nameEn: 'Papaya',
    emoji: '🧡',
    peakMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    offMonths: [],
    seasonalityType: 'mild',
    growingRegions: ['Jawa Timur', 'Jawa Barat', 'Lampung', 'Sulawesi Selatan'],
    priceRange: { low: 6000, high: 18000 },
    ramadanImpact: 'medium',
    description: 'Buah tropis sepanjang tahun yang kaya vitamin A dan enzim papain.',
  },
  {
    id: 'jeruk',
    nameId: 'Jeruk',
    nameEn: 'Orange',
    emoji: '🍊',
    peakMonths: [5, 6, 7, 8],
    offMonths: [12, 1, 2],
    seasonalityType: 'moderate',
    growingRegions: ['Jawa Timur', 'Bali', 'Kalimantan Barat', 'Sumatera Utara'],
    priceRange: { low: 12000, high: 35000 },
    ramadanImpact: 'medium',
    description: 'Buah sitrus segar dengan varietas unggulan Jeruk Bali dan Jeruk Medan.',
  },
  {
    id: 'salak',
    nameId: 'Salak',
    nameEn: 'Snake Fruit',
    emoji: '🫘',
    peakMonths: [12, 1, 2, 3],
    offMonths: [6, 7, 8],
    seasonalityType: 'moderate',
    growingRegions: ['Yogyakarta', 'Bali', 'Jawa Timur', 'Sumatera Utara'],
    priceRange: { low: 10000, high: 30000 },
    ramadanImpact: 'low',
    description: 'Buah bersisik khas Indonesia dengan rasa manis asam yang segar.',
  },
  {
    id: 'duku',
    nameId: 'Duku',
    nameEn: 'Langsat/Duku',
    emoji: '🟡',
    peakMonths: [1, 2, 3],
    offMonths: [6, 7, 8, 9],
    seasonalityType: 'strong',
    growingRegions: ['Sumatera Selatan', 'Jambi', 'Kalimantan Selatan'],
    priceRange: { low: 25000, high: 60000 },
    ramadanImpact: 'low',
    description: 'Buah kecil berkulit tipis dengan daging bening manis dari Palembang.',
  },
  {
    id: 'belimbing',
    nameId: 'Belimbing',
    nameEn: 'Star Fruit',
    emoji: '⭐',
    peakMonths: [7, 8, 9],
    offMonths: [1, 2, 3],
    seasonalityType: 'moderate',
    growingRegions: ['Jawa Timur', 'Jawa Barat', 'DI Yogyakarta'],
    priceRange: { low: 8000, high: 20000 },
    ramadanImpact: 'low',
    description: 'Buah berbentuk bintang dengan rasa manis segar khas Demak.',
  },
  {
    id: 'melon',
    nameId: 'Melon',
    nameEn: 'Melon',
    emoji: '🍈',
    peakMonths: [7, 8, 9],
    offMonths: [12, 1, 2],
    seasonalityType: 'moderate',
    growingRegions: ['Jawa Timur', 'Jawa Tengah', 'NTB'],
    priceRange: { low: 8000, high: 25000 },
    ramadanImpact: 'medium',
    description: 'Buah manis berair yang populer untuk minuman segar dan sop buah.',
  },
  {
    id: 'jambu_biji',
    nameId: 'Jambu Biji',
    nameEn: 'Guava',
    emoji: '💚',
    peakMonths: [1, 2, 3],
    offMonths: [6, 7, 8],
    seasonalityType: 'moderate',
    growingRegions: ['Jawa Timur', 'Jawa Barat', 'Sumatera Utara'],
    priceRange: { low: 6000, high: 20000 },
    ramadanImpact: 'low',
    description: 'Buah kaya vitamin C dengan varietas populer Jambu Kristal dan Merah.',
  },
  {
    id: 'sawo',
    nameId: 'Sawo',
    nameEn: 'Sapodilla',
    emoji: '🤎',
    peakMonths: [11, 12, 1, 2],
    offMonths: [5, 6, 7],
    seasonalityType: 'moderate',
    growingRegions: ['Jawa Timur', 'Jawa Tengah', 'Sumatera Utara'],
    priceRange: { low: 10000, high: 30000 },
    ramadanImpact: 'low',
    description: 'Buah coklat manis legit yang lembut dan kaya serat.',
  },
  {
    id: 'kedondong',
    nameId: 'Kedondong',
    nameEn: 'Ambarella',
    emoji: '💛',
    peakMonths: [1, 2, 3],
    offMonths: [7, 8, 9],
    seasonalityType: 'moderate',
    growingRegions: ['Jawa Barat', 'Jawa Tengah', 'Sumatera Selatan'],
    priceRange: { low: 5000, high: 15000 },
    ramadanImpact: 'low',
    description: 'Buah asam segar yang populer untuk rujak dan asinan.',
  },
  {
    id: 'jambu_mete',
    nameId: 'Jambu Mete',
    nameEn: 'Cashew Apple',
    emoji: '🍐',
    peakMonths: [7, 8, 9],
    offMonths: [1, 2, 3],
    seasonalityType: 'strong',
    growingRegions: ['NTT', 'Sulawesi Tenggara', 'Jawa Timur'],
    priceRange: { low: 50000, high: 120000 },
    ramadanImpact: 'none',
    description: 'Buah semu dengan biji mete bernilai tinggi dari Indonesia Timur.',
  },
  {
    id: 'kesemek',
    nameId: 'Kesemek',
    nameEn: 'Persimmon',
    emoji: '🍅',
    peakMonths: [4, 5, 6],
    offMonths: [10, 11, 12],
    seasonalityType: 'strong',
    growingRegions: ['Jawa Barat', 'Jawa Timur', 'Sumatera Utara'],
    priceRange: { low: 15000, high: 40000 },
    ramadanImpact: 'none',
    description: 'Buah manis lembut berwarna oranye dari dataran tinggi Dieng dan Garut.',
  },
  {
    id: 'nanas',
    nameId: 'Nanas',
    nameEn: 'Pineapple',
    emoji: '🍍',
    peakMonths: [3, 4, 5, 6],
    offMonths: [10, 11, 12],
    seasonalityType: 'moderate',
    growingRegions: ['Lampung', 'Sumatera Utara', 'Jawa Timur', 'Kalimantan Barat'],
    priceRange: { low: 8000, high: 20000 },
    ramadanImpact: 'medium',
    description: 'Buah tropis asam manis yang menjadi komoditas ekspor unggulan Lampung.',
  },
  {
    id: 'sirsak',
    nameId: 'Sirsak',
    nameEn: 'Soursop',
    emoji: '🍏',
    peakMonths: [1, 2, 3, 4],
    offMonths: [7, 8, 9],
    seasonalityType: 'moderate',
    growingRegions: ['Jawa Barat', 'Jawa Timur', 'Sumatera Utara'],
    priceRange: { low: 10000, high: 30000 },
    ramadanImpact: 'low',
    description: 'Buah berduri lunak dengan daging putih asam manis untuk jus segar.',
  },
  {
    id: 'markisa',
    nameId: 'Markisa',
    nameEn: 'Passion Fruit',
    emoji: '💜',
    peakMonths: [6, 7, 8, 9],
    offMonths: [12, 1, 2],
    seasonalityType: 'strong',
    growingRegions: ['Sumatera Utara', 'Sulawesi Selatan', 'NTT'],
    priceRange: { low: 12000, high: 35000 },
    ramadanImpact: 'none',
    description: 'Buah asam segar khas Medan yang terkenal sebagai sirup markisa.',
  },
  {
    id: 'langsat',
    nameId: 'Langsat',
    nameEn: 'Langsat',
    emoji: '🫛',
    peakMonths: [8, 9, 10],
    offMonths: [2, 3, 4],
    seasonalityType: 'strong',
    growingRegions: ['Kalimantan Selatan', 'Kalimantan Timur', 'Sumatera Selatan'],
    priceRange: { low: 15000, high: 40000 },
    ramadanImpact: 'none',
    description: 'Buah kecil bergerombol mirip duku dengan rasa manis asam segar.',
  },
  {
    id: 'cempedak',
    nameId: 'Cempedak',
    nameEn: 'Cempedak',
    emoji: '🟤',
    peakMonths: [11, 12, 1],
    offMonths: [5, 6, 7],
    seasonalityType: 'strong',
    growingRegions: ['Kalimantan Barat', 'Sumatera Utara', 'Riau'],
    priceRange: { low: 10000, high: 25000 },
    ramadanImpact: 'low',
    description: 'Kerabat nangka dengan aroma kuat dan daging buah manis legit.',
  },
  {
    id: 'nangka',
    nameId: 'Nangka',
    nameEn: 'Jackfruit',
    emoji: '💛',
    peakMonths: [10, 11, 12],
    offMonths: [4, 5, 6],
    seasonalityType: 'moderate',
    growingRegions: ['Jawa Timur', 'Jawa Barat', 'Sumatera Utara', 'Lampung'],
    priceRange: { low: 8000, high: 20000 },
    ramadanImpact: 'low',
    description: 'Buah terbesar di dunia dengan daging kuning manis wangi untuk es campur.',
  },
  {
    id: 'sukun',
    nameId: 'Sukun',
    nameEn: 'Breadfruit',
    emoji: '🫒',
    peakMonths: [3, 4, 5],
    offMonths: [9, 10, 11],
    seasonalityType: 'moderate',
    growingRegions: ['Jawa Barat', 'Jawa Tengah', 'DI Yogyakarta'],
    priceRange: { low: 8000, high: 20000 },
    ramadanImpact: 'medium',
    description: 'Buah bertepung yang populer digoreng sebagai camilan dan lauk.',
  },
  {
    id: 'matoa',
    nameId: 'Matoa',
    nameEn: 'Matoa',
    emoji: '🫐',
    peakMonths: [3, 4, 5],
    offMonths: [9, 10, 11],
    seasonalityType: 'strong',
    growingRegions: ['Papua', 'Papua Barat', 'Maluku'],
    priceRange: { low: 20000, high: 60000 },
    ramadanImpact: 'none',
    description: 'Buah endemik Papua yang langka dengan rasa perpaduan leci dan rambutan.',
  },
  {
    id: 'jambu_air',
    nameId: 'Jambu Air',
    nameEn: 'Water Apple',
    emoji: '🩷',
    peakMonths: [11, 12, 1, 2],
    offMonths: [5, 6, 7],
    seasonalityType: 'moderate',
    growingRegions: ['Jawa Timur', 'Jawa Tengah', 'DI Yogyakarta'],
    priceRange: { low: 8000, high: 25000 },
    ramadanImpact: 'low',
    description: 'Buah renyah berair dengan varietas Citra dan Deli Hijau yang populer.',
  },
  {
    id: 'buah_naga',
    nameId: 'Buah Naga',
    nameEn: 'Dragon Fruit',
    emoji: '🐉',
    peakMonths: [6, 7, 8, 9, 10],
    offMonths: [1, 2],
    seasonalityType: 'moderate',
    growingRegions: ['Jawa Timur', 'Bali', 'NTB', 'Kalimantan Selatan'],
    priceRange: { low: 15000, high: 40000 },
    ramadanImpact: 'medium',
    description: 'Buah eksotis berwarna merah menyala yang kaya antioksidan.',
  },
  {
    id: 'leci',
    nameId: 'Leci',
    nameEn: 'Lychee',
    emoji: '🩷',
    peakMonths: [12, 1, 2],
    offMonths: [5, 6, 7, 8, 9],
    seasonalityType: 'strong',
    growingRegions: ['Sumatera Utara', 'Jawa Timur', 'Jawa Barat'],
    priceRange: { low: 20000, high: 60000 },
    ramadanImpact: 'medium',
    description: 'Buah mungil berkulit merah dengan daging bening manis harum.',
  },
  {
    id: 'lengkeng',
    nameId: 'Lengkeng',
    nameEn: 'Longan',
    emoji: '🫧',
    peakMonths: [1, 2, 3],
    offMonths: [6, 7, 8],
    seasonalityType: 'strong',
    growingRegions: ['Jawa Timur', 'Jawa Tengah', 'DI Yogyakarta'],
    priceRange: { low: 20000, high: 50000 },
    ramadanImpact: 'low',
    description: 'Buah mata naga kecil manis dengan daging bening segar mirip leci.',
  },
];

export const getFruitById = (id: string): FruitData | undefined =>
  FRUITS.find((f) => f.id === id);

export const getFruitsByRamadanImpact = (
  impact: FruitData['ramadanImpact']
): FruitData[] => FRUITS.filter((f) => f.ramadanImpact === impact);

export const getYearRoundFruits = (): FruitData[] =>
  FRUITS.filter((f) => f.offMonths.length === 0);
